export const episodesPageMsg = {
  title: "Episodes",
  timelinePageTitle: "Timeline | Episodes",
  timelineDescription: "兄弟日記 全エピソードのタイムライン。",
  timelineSeasonNav: "シーズン切替",
  timelineJumpNav: "シーズンへジャンプ",
  alternateTag: "Another Episode",
  seasonTimelineLabel: "timeline",
  episodeSelectionEmpty: "エピソードを選択してください。",
  noEpisodesYet: "No episodes yet.",
  logPageTitle: "Episodes",
  logSuffix: "のログ",
  logNavigation: "ログナビゲーション",
  deletedCanonBadge: "削除史実",
  previousEpisodeArrow: "‹",
  nextEpisodeArrow: "›",
  previousEpisodeMove: "前の話へ移動",
  nextEpisodeMove: "次の話へ移動",
  detailImageAlt: (title: string) => `${title} main visual`,
  redirecting: "移動中…",
  logInfo: {
    scenarioAuthor: "シナリオ制作者 :",
    scenarioDistribution: "シナリオ頒布先 :",
    adaptedScenario: "改変シナリオ :",
    adaptedScenarioLink: "該当ページへのリンク",
  },
} as const;
