export const episodesPageMsg = {
  timelinePageTitle: "Timeline | Episodes",
  timelineDescription: "兄弟日記 全エピソードのタイムライン。",
  timelineSeasonNav: "シーズン切替",
  timelineJumpNav: "シーズンへジャンプ",
  alternateTag: "Another Episode",
  deletedEpisodeTag: "――",
  seasonTimelineLabel: "timeline",
  episodeSelectionEmpty: "エピソードを選択してください。",
  noEpisodesYet: "No episodes yet.",
  logSuffix: "のログ",
  logNavigation: "ログナビゲーション",
  previousEpisodeMove: "前の話へ移動",
  nextEpisodeMove: "次の話へ移動",
  thumbnailAlt: (title: string) => `${title} main visual`,
  logInfo: {
    scenarioAuthor: "シナリオ制作者 :",
    scenarioDistribution: "シナリオ頒布先 :",
    adaptedScenario: "改変シナリオ :",
    adaptedScenarioLink: "URL",
  },
} as const;
